### PR TITLE
Featured Events Module (Issue #15)

### PR DESCRIPTION
**Pull request by esopp**
Adds featured events HTML, classes, and behavior (both desktop and mobile, contrary to the branch name).

Some of the basic element styling may need to be reconciled with or moved to global.css

Because featured event divs are displayed in a row in desktop mode, the height of each event is adjusted in main.js to match the height of the tallest div.

### CODE REVIEW

**Comment by esopp** [comment]
Realized the sizing/spacing of certain elements could match the png a bit more closely, so I've tried to refine that a bit since the pull request. Pushing to the branch now, hopefully this will not confuse github at all.

**Comment by wnstn** [comment]
@esopp all of the styling and HTML looks phenomenal! Thanks so much. I just did a bit of experimentation and I think we can refactor the JS a bit to make it easier to read. Here's my thoughts.

1. The mobile styling can be default rather than set by JS, just add a css selector of `height: 10px` to `.featured-events .responsive-spacer`. Our desktop JS can override it. You can also set the minimum height to be 30px on desktop in the CSS if you want.

2. I think we can simplify the JS to something like below; it's the same idea as yours but taking advantage of how jQuery allows us to get height and such. This is the desktop section of your `if` statement:

````javascript

      var tallestElement = 0;
      var $featuredEvents = $('.custom-featured-event');
      var spacerMinHeight = 30;

      $featuredEvents.each(function(){
        // loop through elements and figure out which is the tallest one
        tallestElement = $(this).height() > tallestElement ? $(this).height() : tallestElement;
      })

      $featuredEvents.each(function(){
        var $el = $(this);
        // we are looking for the tallest featured event to make sure all elements
        // are the same height
        var currentHeight = $el.height();
        $el.find('.responsive-spacer').height(tallestElement - currentHeight + spacerMinHeight);
      });
````

Let me know if any of that doesn't make sense or if I missed something you were doing! I tested it out locally and it seems to have the same results as yours but I may have misunderstood everything you were factoring in.

These are the only changes I have, everything else is good!

**Comment by esopp** [comment]
Possibly I added some kind of error inadvertently when I copy-pasted (this is very possible and I will keep testing), but when I run the code from point 2, I seem to run into issues with jquery not always returning the correct height for each .custom-featured-event when I resize the browser window (I suspect this has something to do with the fact that the .custom-featured-event elements are pseudo-elements, with undefined height until they are rendered-- adding the heights of the child elements of each featured event was my way around this issue when it originally cropped up for me).

Definitely applying the suggested variable names, and sorry I didn't have an opportunity earlier in the day to work on any of this.

**Comment by esopp** [comment]
@wnstn I should have asked directly, though-- should I merge this branch as is? I did change some variable names, but I couldn't overcome the pseudo-element issue that was happening with the suggested rewrite.

**Comment by wnstn** [comment]
Sorry @esopp, missed this email but merge at will!

**Pull request merged**
