### PR TITLE
Styling Find Your Legislator Page

### PR DESCRIPTION
**Pull request by wnstn**
Desktop styles:

image

Mobile styles:

image

Button styles need to be added to global styling and they will apply here.

### CODE REVIEW

**Comment by wnstn** [comment]
Addresses #59

**Comment by sarawb** [comment]
- Instructional copy for the address field is in the CMS -- I don't think we want this bold styling for it. Copy is part of a list of steps to contacting your rep (this is step 1) all on one page, so it should be: 

> *1. Find your state legislators*
>Enter your address and we'll show you who represents you in Harrisburg, how to reach them, and  whether they already sponsor current redistricting bills.

- The initial address field/button looks out of sync with the site -- we should use the green button CTA style for Change Address (and also for the initial button, not sure what that says currently, but I think it would be fine as just "Find legislators" 

- I would suggest we don't use bullets -- they don't really communicate contact info clearly.  

- Order of information seems off and it's missing whether they are a sponsor or not. Order should be: 
1. Name
2. Party (can we have this display as just (R) or (D) after their name instead of "Democratic"?)  
3. Sponsors SB 22 (if senator) or Sponsors HB 722 (if House) OR Does not Sponsor 
4. Contact information - I would put this in an H5
5. Phone number 
6. Email address 
7. Address -- question: this shows a PO box but FDPA is advocating for a lot of in-person visits. What data is available in the API? Just mailing? Are there multiple addresses?

**Comment by wnstn** [comment]
@sarawb I will remove the bullets, and once this is incorporated to a Craft template we'll output the instructional text from the admin.

Button text will use the green CTA.

Will update the data with the corresponding details that you mention. The data object returned only has mailing address but it does have their URL so I think we can add a "visit their site to find local offices" link?

image

**Comment by wnstn** [comment]
Merging this in as WIP and will refer back to comments for future work.

**Pull request merged**
