### PR TITLE
Update readme.md

### PR DESCRIPTION
**Pull request by RyKilleen**
For my setup, `localhost:8888` was non-responsive but `localhost:8888/admin` showed the begin button. Is this true for everyone?

### CODE REVIEW

**Comment by onebrightlight** [comment]
That sounds like you need to import the database still.

**Comment by wnstn** [comment]
@onebrightlight is that not the case anymore? Forgive me I'm not too familiar on Craft here.

**Comment by onebrightlight** [comment]
@wnstn if the admin view shows a "begin" button, it means the database exists, but hasn't been imported usually.

**Comment by esopp** [comment]
I never had a "begin" button, but localhost:8888 shows me this index page: 
screen shot 2017-04-21 at 5 06 22 pm


And localhost:8888/admin is "Not Found."

This isn't an obstacle for me right now (I can test the menu I'm working on at localhost:8888/fdpa/public/assets/theme because I put the fdpa directory in MAMP's htdocs folder), but I feel like I should document my mistakes as I'm probably the least experienced member of the team right now, and therefore the most likely to encounter pitfalls that future newbies must be warned about...

**Comment by onebrightlight** [comment]
@esopp you need to point the domain to the correct directory. It should be called `public`

**Comment by wnstn** [comment]
👍 Going to go ahead and merge just because this is v helpful and minor.

**Pull request merged**
