### PR TITLE
reduce list font size and add region icons to column headers

### PR DESCRIPTION
**Pull request by esopp**
Addresses issue #152 

@sarawb might want to approve the placement of the regional icons before merge.

### CODE REVIEW

**Comment by sarawb** [comment]
@esopp Hi! I don't have the site spun up locally, so I can't see that placement, but Jason's design feedback was to align with Events, so to the right of the headers makes sense to me. If you want to show me a screenshot of the page I'd be happy to review or we can merge and then tweak as needed!

**Comment by wnstn** [comment]
@esopp I'm not seeing this be output on the page locally?

**Comment by esopp** [comment]
@sarawb this is what it looks like on my local version of the site:
fdpa group listing

@wnstn after checking to make sure that this is the correct version of this stylesheet (and it does seem to be), my only idea for why you might not be seeing it is that one of us might be looking at/working on the wrong page? I'm working on [hostname]/local-groups, but NOT [hostname]/local-group/[group-name] (for example localhost:8888/local-groups/philadelphia).

**Comment by sarawb** [comment]
@wnstn did you figure out what's going on here?

**Comment by wnstn** [comment]
@esopp just confirmed it's working locally now, thanks for doing this!

**Pull request merged**
